### ISSUE TITLE
Version v0.1

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-sublime#1]
Following https://github.com/smallcloudai/refact-vs-classic/ , we need a first version of a plugin for Sublime Text that starts refact-lsp server, has completion, status bar, settings, and that's about it.

Completion should behave generally like in VS Code, more details about multiline and single line completion are [here in a VS Classic issue](https://github.com/smallcloudai/refact-vs-classic/issues/9) and [here is some more](https://github.com/smallcloudai/refact-vs-classic/issues/6).

Clarification: this has nothing to do with completions that go inside a popup. Here we are only interested in inline completions (multiline or single line), also known as "grey text" or "ghost text".

Refact-LSP is an executable file that [gets built here](https://github.com/smallcloudai/refact-lsp/actions), download one for your platform, run it with --help to see what kind of options it accepts. 

The relevant LSP part is textDocument/didOpen, textDocument/didChange, textDocument/didClose, workspace/didDeleteFiles -- to inform the LSP server about the source files open or changed. This is used for context, for a good completion for file1 probably it needs a context from file2. That's why refact-lsp needs those calls to happen.

The completion itself is a LSP call `refact/getCompletions`, but there's [an effort to switch to a more standard 3.18](https://github.com/smallcloudai/refact-lsp/issues/3).

Status bar [like in this VS issue](https://github.com/smallcloudai/refact-vs-classic/issues/8) needs an idle state, rotating icon when it asks for a new completion, and an error state that shows text error in a tooltip.

Settings can be similar to VS Code settings, those are mainly go directly to refact-lsp command line. One that doesn't is "pause", it should be accessible via a context menu in the status bar or a hotkey -- an ability to pause completions if they get annoying in some cases.

This bounty supersedes the previous attempt [over here](https://github.com/smallcloudai/refact-lsp/issues/1) that got stalled.

**Comment by b4s36t4** [comment]
@olegklimov Would love to work on this.

**Comment by b4s36t4** [comment]
Please assign.

**Comment by digital-phoenix** [comment]
I'd love to work on this @olegklimov could you assign it to me?

**Comment by ayewo** [comment]
@olegklimov ✋

**Comment by Ahmadkhan02** [comment]
@olegklimov I would also love to work on this one

**Comment by Ahmadkhan02** [comment]
@olegklimov can you elaborate some more upon how you need the status bar to be?

**Comment by digital-phoenix** [comment]
![2023-12-02 14 53 05](https://github.com/smallcloudai/refact-sublime/assets/350208/538ec370-2436-4b88-8ef8-570d96822814)

Progress update: Single line completions are now functional

**Comment by olegklimov** [comment]
Hi everyone. I'll assign this to James because he's good, we worked with him before.

**Comment by ayewo** [comment]
@olegklimov No worries.

(The question on my mind and I'm sure on others' is: how can we *show you* if we are any good if we are never given chance when new tasks are available? Perhaps you have a few low-ticket tasks that you are planning to throw open to everyone? You don't have to answer but it would nice if you did.)

**Comment by ijif** [comment]
any updates on this?

**Comment by olegklimov** [comment]
> any updates on this?

@digital-phoenix has a first version, but no one checked it yet, because we got stuck with the VS Classic plugin. We'll try to unstuck it as soon as possible.

**Comment by jigarh12** [comment]
Hey, I would like to work on this project. 
My name is Jigar Hundia, I am a Automation and Robotics Student. I have expertise in Python, HTML5, CSS and C/C++. I also have a Python Developer Micro degree Certificate. So, I am enthusiast to work on this project.
