### ISSUE TITLE
Make settings accessible via menu

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-sublime#12]
It's not there currently:

<img width="626" alt="image" src="https://github.com/smallcloudai/refact-sublime/assets/18546213/e74df6c1-ba4e-4239-8d0f-9c8546fc5aee">

**Comment by hazratisulton** [comment]
https://github.com/smallcloudai/refact-sublime/pull/15  settings available ![изображение](https://github.com/smallcloudai/refact-sublime/assets/140423660/4ce29f2c-9672-43d3-ae35-023b1629d4a8)

**Comment by hazratisulton** [comment]
Rechecked https://github.com/smallcloudai/refact-sublime/pull/16 - available.
