### ISSUE TITLE
Status bar is flickering

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-sublime#13]
Is there a timer that updates the status bar all the time?

One solution might be to change status bar whenever Refact plugin actually works, and leave it alone in other times.

https://github.com/smallcloudai/refact-sublime/assets/18546213/f7aeacef-3750-4b23-9c21-47220d941d1e

**Comment by hazratisulton** [comment]
Checked https://github.com/smallcloudai/refact-sublime/pull/16 - can't reproduce.
