### ISSUE TITLE
Need LSP workspace folders and events

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-sublime#4]
Now refact-lsp receives:

```
2024-02-07T09:12:02.530871Z  INFO refact_lsp::lsp:180: LSP client_info None
2024-02-07T09:12:02.530875Z  INFO refact_lsp::lsp:184: LSP workspace_folders RwLock { data: None }
```

But it needs workspace folders to index the files inside. I have two Sublime windows open, with different paths. Both need to be visible in workspace_folders.

Another problem is it needs these LSP events for specific files:

did_open
did_change
did_save
did_close

And finally for statistics we need `handle_v1_snippet_accepted` (actually an analog of this in LSP RPC) when a grey text code completion is accepted (Tab).

**Comment by reymondzzzz** [comment]
I added refact/acceptCompletion method. Params: {snippet_telemetry_id: int}. snippet_telemetry_id came from refact/getCompletions

**Comment by digital-phoenix** [comment]
The code already sends didopen and didchange events with the corresponding file name.

**Comment by olegklimov** [comment]
> didopen
I didn't see any open event, it needs to post 'open' for each file open on Sublime startup for example.

**Comment by digital-phoenix** [comment]
Everytime the user interacts with a new file refact_sessions calls  load_document which sends a didOpen event. It even handles temporary unnamed files.

**Comment by digital-phoenix** [comment]
@olegklimov is the issue that the plugin only provides open messages for files after the user interacts with them? Do you want the plugin to send didOpen messages on launch as well?

**Comment by olegklimov** [comment]
I've tested quickly again, it's true "changed" arrives when I edit the code:
```
changed ...rc/vecdb/vectorizer_service.rs, total time 83.583µs
```
But I don't see "opened" whatever I do.

> on launch as well

Sure.

**Comment by olegklimov** [comment]
workspaces -- doesn't work, workspace_folders always empty list []
didOpen -- doesn't work (at start, clicking in a file the tree, Ctrl+O -- all three ways to open a file don't produce 
didChange -- ✅ works
didClone -- ✅ works

**Comment by digital-phoenix** [comment]
@olegklimov how do you want workspaces to work here? Are you sure didOpen isn't working I can see it's sending the message to the server and it's using the same mechanism as the ones that are working.

**Comment by olegklimov** [comment]
> workspaces 

You can open a folder in Sublime, a new window opens, and all the tools like search work for all the files in that folder. So that's a good candidate for a workspace dir, organized in a list for all open windows that have folders associated.


> didOpen

I noticed that too. In Sublime console there's a message, and then it gets lost somewhere along the way. `refact-lsp` has no problem catching didOpen:

`cat ~/.cache/refact/logs/rustbinary.2024-03-05 | grep --color "opened "`

<img width="400" alt="image" src="https://github.com/smallcloudai/refact-sublime/assets/18546213/a9c931e5-6f7a-4e16-afc3-c385b771e4b0">

**Comment by digital-phoenix** [comment]
So you only want a workspace to be created if the user directly opens a folder? I'm not sure what those opened messages are indicating? Are they showing didOpen messages being received on the server or are they showing something else entirely?

**Comment by olegklimov** [comment]
> created 

reported 

> workspace to be created if the user directly opens a folder

or starts Sublime so all the windows are restored back as they were the previous time

> showing didOpen messages being received

yes, didOpen messages sent by VSCode and received fine, demonstrating didOpen works on the server side

**Comment by hazratisulton** [comment]
Checked https://github.com/smallcloudai/refact-sublime/pull/16.
workspaces -- doesn't work
didOpen -- working (clicking in a file the tree, Ctrl+O)
didOpen at start - message appears when you click in the selected file

**Comment by hazratisulton** [comment]
Checked.
workspaces -  work, workspace_folders shows open folders.
didOpen -- working (clicking in a file the tree, Ctrl+O)
didOpen at start - message appears when you click in the selected file (In VS Code message appears when you click on the title of the selected file)
