### ISSUE TITLE
Fix closing brackets

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-sublime#5]
It's important to delete spaces before asking the model, because there should be a way for the model to suggest code with less indent. Typical example of this:

```
int main()
{
    printf("Hello world!\n");
    |
```

Now the completion is "}", but it will not work unless there are no spaces on that line. With spaces, the model is constrained to "    }".

**Comment by olegklimov** [comment]
No, it doesn't work. Grey text looks like this:

<img width="215" alt="image" src="https://github.com/smallcloudai/refact-sublime/assets/18546213/5c7e3614-da44-455e-8147-017e921a0518">

And after Tab it accepts it like this:

<img width="246" alt="image" src="https://github.com/smallcloudai/refact-sublime/assets/18546213/33037f7e-c66c-479c-9d75-5aaaac02fa88">

**Comment by hazratisulton** [comment]
Checked https://github.com/smallcloudai/refact-sublime/pull/16 - working.
