### ISSUE TITLE
Completion doesn't start after "pause refact"

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact-sublime#7]
**Steps to reproduce:**
Checking completion - completion is working
Press "pause refact" (in Tools menu) and check - completion is not working (OK)
Press pause again - check completion.

**Expected result:**
Completion started and working.

**Actual result:**
Completion not working.
No error messages.
In console:
```
reloading settings Packages/User/refact.sublime-settings
reloading settings Packages/User/refact.sublime-settings
```
**Additional info:**
If you restart sublime, completion still won't work. If then press "pause refact", console will display the following:
`Traceback (most recent call last):
  File "/snap/sublime-text/156/opt/sublime_text/Lib/python38/sublime_plugin.py", line 1704, in run_
    return self.run(edit)
  File "/home/fupfv/.config/sublime-text/Packages/refact/__init__.py", line 128, in run
    refact_session_manager.get_session(self.view).clear_completion()
AttributeError: 'NoneType' object has no attribute 'get_session'
reloading settings Packages/User/refact.sublime-settings`
If you manually change "pause_completion" setting to false in .config/sublime-text/Packages/User/refact.sublime-settings, completion will work.

Versions:
Refact 0.0.1
Sublime Text? Build 4169

**Comment by olegklimov** [comment]
1. Pause should be a command accessible in .sublime-keymap:

```
{
 { "keys": ["super+p"], "command": "refact_pause" },
}
```

2. Documented in README
3. Icon should be different in the status bar, like ⏸️

**Comment by olegklimov** [comment]
Pause problem: I see `Sublime Text/Packages/User/refact.sublime-settings`:

```
{
        "pause_completion": true,
}
```

my settings are in `Sublime Text/Packages/refact/refact.sublime-settings`. I suspect the file in User replaces all my settings from the file in Packages/refact, including all the settings that make the plugin work.

**Comment by hazratisulton** [comment]
https://github.com/smallcloudai/refact-sublime/pull/15 - fixed

**Comment by hazratisulton** [comment]
Checked https://github.com/smallcloudai/refact-sublime/pull/16 - completion and pause icon working,
