### ISSUE TITLE
Sometimes grey text doesn't appear

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-sublime#8]
...then you can press Space (or any character), then Backspace, the grey text appears.

**Comment by hazratisulton** [comment]
Example:
No grey text after moving to a new line (pressed Enter):
![image](https://github.com/smallcloudai/refact-sublime/assets/140423660/1cda9ddc-00af-4998-98b9-af53349f9235)
You have to press Backspace four times for the grey text to appear:
![image](https://github.com/smallcloudai/refact-sublime/assets/140423660/a015d329-58d0-4b9d-a7e2-3998643c64ec)

**Comment by olegklimov** [comment]
@hazratisulton that's the same as https://github.com/smallcloudai/refact-sublime/issues/5 on your screenshots.

**Comment by olegklimov** [comment]
Start with this:

<img width="391" alt="image" src="https://github.com/smallcloudai/refact-sublime/assets/18546213/1342fff5-2745-4dca-8128-15d380aeaf48">

then quickly type "from":

<img width="365" alt="image" src="https://github.com/smallcloudai/refact-sublime/assets/18546213/93ae5620-bdb2-438e-9ad5-70d6506377ff">

popup will flash and disappear, no gray text

<img width="373" alt="image" src="https://github.com/smallcloudai/refact-sublime/assets/18546213/d7e9cae3-98d7-416d-b774-af2f348352c5">

Space, backspace => grey text from cache.

**Comment by hazratisulton** [comment]
> Start with this:
> 
> <img alt="image" width="391" src="https://private-user-images.githubusercontent.com/18546213/305038658-1342fff5-2745-4dca-8128-15d380aeaf48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5ODQ5NzgsIm5iZiI6MTcwOTk4NDY3OCwicGF0aCI6Ii8xODU0NjIxMy8zMDUwMzg2NTgtMTM0MmZmZjUtMjc0NS00ZGNhLTgxMjgtMTVkMzgwYWVhZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDExNDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NDhiN2NkZTdkOGNkNTczNjcyN2UxNGM1MmZjZWJmZGZmZGM3YTgyN2Y4MjFmZDMwMmFiMmU2NjQzYTY2NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Un6M34oU0EgmPlDpQPi_tsk_tk0-qoCEvjY_8uMpge4">
> then quickly type "from":
> 
> <img alt="image" width="365" src="https://private-user-images.githubusercontent.com/18546213/305038830-93ae5620-bdb2-438e-9ad5-70d6506377ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5ODQ5NzgsIm5iZiI6MTcwOTk4NDY3OCwicGF0aCI6Ii8xODU0NjIxMy8zMDUwMzg4MzAtOTNhZTU2MjAtYmRiMi00MzhlLTlhZDUtNzBkNjUwNjM3N2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDExNDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNTgyYmY2ZTViMGViOTAxMTY4OWY1YTFhMmViZTE0NjZhYTliYjkyYjQxMTE1ZWMzNTdmNTJkM2I4NTJiM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eujhgMRWmxWIZ1IlfyoJ_mbiWJ7WyCpV2eFOI1e5BPE">
> popup will flash and disappear, no gray text
> 
> <img alt="image" width="373" src="https://private-user-images.githubusercontent.com/18546213/305039165-d7e9cae3-98d7-416d-b774-af2f348352c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5ODQ5NzgsIm5iZiI6MTcwOTk4NDY3OCwicGF0aCI6Ii8xODU0NjIxMy8zMDUwMzkxNjUtZDdlOWNhZTMtOThkNy00MTZkLWI3NzQtYWYyZjM0ODM1MmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDExNDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZDQ4YTcwZTA0YmFmMThlNzBiODBkYTVmZDVhZGIxNTkwZGQ5MDM5ZDM2ZTlmZWE2OTAwNzYxZmEzY2FmYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0fhbIEcstLOXMzQ9xBr_eq3D-sTfmRD38NuCuq-olt8">
> Space, backspace => grey text from cache.

This problem still here but without "popup will flash and disappear":

[Screencast from 10-03-24 02:50:50.webm](https://github.com/smallcloudai/refact-sublime/assets/140423660/ff10c1a4-bfa6-4feb-a519-633e5593e4a7)

**Comment by hazratisulton** [comment]
Checked https://github.com/smallcloudai/refact-sublime/pull/16 - fixed.
