### ISSUE TITLE
[WIN] When running Sublime, when refact-lsp starts, PowerShell window opens with refact-lsp process

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact-sublime#9]
Just open Sublime with Refact plugin installed and a PowerShell window window opens with refact-lsp process.
![изображение](https://github.com/smallcloudai/refact-sublime/assets/140423660/c539e76f-a5b9-47ec-902c-935847d8b556)
[sublime_console.log](https://github.com/smallcloudai/refact-sublime/files/14288755/sublime_console.log)

**Versions:**
Sublime plugin v 0.0.1
Sublime Text Build 4169

**Comment by olegklimov** [comment]
The same binary run by VS Code plugin doesn't produce a powershell window.

**Comment by hazratisulton** [comment]
https://github.com/smallcloudai/refact-sublime/pull/15 - fixed
